### ISSUE TITLE
String regExp support ?

### ISSUE THREAD

**Issue by 1fabiopereira** [voltraco/dml#4]
- Validation support exists with regExp ?

Ex:

```
String uuid {
	required true
	regExp  /[0-9]{1,3}.[0-9]{1,3}/
}
```

**Comment by heapwolf** [comment]
yes that works, but it would be like this...

```js
String uuid {
  required true
  match /[0-9]{1,3}.[0-9]{1,3}/
}
```

Maybe we could add `regexp` as an alias to `match`, thoughts?

**Comment by 1fabiopereira** [comment]
in my view regExp is more suggestive, adding this alias can help ! 😄

**Comment by heapwolf** [comment]
Ok, should be good. I aded it in e819a65d682332cf085a76b61d549a33aaeb7ab6. And a [passing test](https://github.com/voltraco/dml/commit/e819a65d682332cf085a76b61d549a33aaeb7ab6#diff-a55c3a863e8dda080a0ec75a5abe6027). So we can use `regexp` or `regExp`. Also updated the docs :)

**Comment by 1fabiopereira** [comment]
Nice man 😀
